Upgrade dependencies (#295)
* upgrade dependencies

* fix wrong base installation

ERROR: Cannot uninstall 'terminado'. It is a distutils installed project
and thus we cannot accurately determine which files belong to it which
would lead to only a partial uninstall.

* rengenerated pip-requirements